version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: appflowy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: appflowy
      POSTGRES_USER: appflowy
      POSTGRES_PASSWORD: QRrJfWxKooDKen0sEpAgfNdCpSsKQgFy
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - appflowy-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appflowy"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: appflowy-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - appflowy-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  gotrue:
    image: supabase/gotrue:v2.151.0
    container_name: appflowy-gotrue
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://appflowy:QRrJfWxKooDKen0sEpAgfNdCpSsKQgFy@postgres:5432/appflowy?search_path=auth
      GOTRUE_SITE_URL: http://34.42.130.249
      GOTRUE_URI_ALLOW_LIST: http://34.42.130.249
      GOTRUE_JWT_SECRET: FhVkDAifsfPtATCo9ygy4mFsUEotg6O2
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_EXTERNAL_GOOGLE_ENABLED: false
      GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: 
      GOTRUE_EXTERNAL_GOOGLE_SECRET: 
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: http://34.42.130.249/auth/callback
      GOTRUE_DISABLE_SIGNUP: false
      GOTRUE_EXTERNAL_EMAIL_ENABLED: true
      GOTRUE_MAILER_AUTOCONFIRM: true
      GOTRUE_SMTP_ADMIN_EMAIL: admin@example.com
      GOTRUE_SMTP_HOST: 
      GOTRUE_SMTP_PORT: 587
      GOTRUE_SMTP_USER: 
      GOTRUE_SMTP_PASS: 
      GOTRUE_SMTP_SENDER_NAME: AppFlowy Workspace
      API_EXTERNAL_URL: http://34.42.130.249
    ports:
      - "9999:9999"
    networks:
      - appflowy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: appflowy-nginx
    restart: unless-stopped
    depends_on:
      - gotrue
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
    networks:
      - appflowy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  appflowy-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  nginx_cache:
